name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24' # The Go version to download (if necessary) and use.
      - name: Install dependencies
        run: |
          go mod download
      - name: download golangci.yml
        run: |
          [[ ! -f ".golangci.yml" ]] && curl -kfsSL -O https://raw.githubusercontent.com/worldline-go/guide/main/lint/.golangci.yml || true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --issues-exit-code 0 --output.checkstyle.path ${{ github.workspace }}/golangci-lint-report.out ./...
      - name: Run tests
        run: |
          go test -coverprofile=coverage.out -json ./... > test-report.out
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ env.REPOSITORY_NAME }}
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.go.tests.reportPaths=test-report.out
            -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report.out
            -Dsonar.sources=.
            -Dsonar.exclusions=**/vendor/**,**/*_test.go
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
